[32m2025-02-13 02:50:07 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 53f882c2-83f9-4945-a32a-850ccf73e114 - 329512 - LOGS_CAPTURED - Started capturing logs in process (pid: 329512).
[32m2025-02-13 02:50:07 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 53f882c2-83f9-4945-a32a-850ccf73e114 - 329512 - preprocessed_data - STEP_START - Started execution of step "preprocessed_data".
[32m2025-02-13 02:50:07 -0300[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 53f882c2-83f9-4945-a32a-850ccf73e114 - preprocessed_data - Loading file from: /home/bajiks/code/Bajiks/ITBA/final-project/dagster_home/storage/scores_users_movies using PickledObjectFilesystemIOManager...
[32m2025-02-13 02:50:07 -0300[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 53f882c2-83f9-4945-a32a-850ccf73e114 - 329512 - preprocessed_data - STEP_FAILURE - Execution of step "preprocessed_data" failed.

dagster._core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "scores_users_movies" of step "preprocessed_data"::

FileNotFoundError: [Errno 2] No such file or directory: '/home/bajiks/code/Bajiks/ITBA/final-project/dagster_home/storage/scores_users_movies'

Stack Trace:
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/execution/plan/inputs.py", line 621, in _load_input_with_input_manager
    value = input_manager.load_input(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/storage/upath_io_manager.py", line 406, in load_input
    return self._load_single_input(path, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/storage/upath_io_manager.py", line 273, in _load_single_input
    obj = self.load_from_path(context=context, path=path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/dagster/_core/storage/fs_io_manager.py", line 283, in load_from_path
    with path.open("rb") as file:
         ^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/envs/mlops-tp-final/lib/python3.12/site-packages/upath/implementations/local.py", line 134, in open
    return PosixPath.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bajiks/.pyenv/versions/3.12.4/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0m
